### ISSUE TITLE
Image bound expands by itself when cropping

### ISSUE THREAD

**Issue by marano** [filestack/filestack-js#71] opened 2017-11-29 12:58 UTC
(I originally posted this bug to filestack-react at https://github.com/filestack/filestack-react/issues/36)

# Versions
filestack-react 1.3.8
filestack-js 0.9.7

# How to reproduce it
1 - Open picker
2 - Select photo
3 - Reduce both sides of the photo crop area
4 - Click at one corner of the crop area and expand it to match the photo limit

# What happens
The opposite side bounds expand a little bit each time. But the faster the movement the more it expands.

# Expected behaviour
Only the side I am dragging should have its bounds resized

# Video
![bug](https://user-images.githubusercontent.com/52855/33271475-80b3472c-d36e-11e7-9188-27071585979b.gif)

**Comment by velveteer** [comment] 2017-11-29 16:36
@marano Thanks for reporting. Can you try upgrading to the latest filestack-js (currently 0.9.12) and confirm if this behavior persists? 

Can you also provide browser information for this issue?

**Comment by marano** [comment] 2017-11-29 17:00
@velveteer I can confirm the issue persists on 0.9.12. It is reproducible on Chrome, Safari and Firefox on macOS High Sierra, didn't try other systems.

**Comment by velveteer** [comment] 2017-11-29 17:16
@marano Thanks. I was able to reproduce on 0.9.12 when providing an aspect ratio to the crop settings. I believe this is a bug with cropperjs: https://github.com/fengyuanchen/cropperjs/issues/222, which was only partially addressed, because I am seeing this bug when resizing with the top-left and top-right handles.

I will look into resolving this in cropperjs if possible, but I cannot make any guarantees on when I will have time to make a PR for them. For now we will track this as a bug.

**Closed** 2019-05-22 12:28 UTC
Labels: bug
