### ISSUE TITLE
filestack-js on npm v1.6.0 has an es6 dependency

### ISSUE THREAD

**Issue by graphographer** [filestack/filestack-js#155] opened 2018-10-04 15:16 UTC
I'm using Gulp/Browserify to bundle and minify my vendor dependencies.

The minifier is unable to minify something from filestack-loader (which I assume is a dep of filestack-js) because it has ES6 syntax in rit.

Can you suggest a workaround or push a properly transpiled fix? I tried for several hours to get my Gulp task to transform it via Babelify, but no dice.

**Comment by graphographer** [comment] 2018-12-19 16:07
Hi, any word on this? in filestack-loader's package.json, the "browser" field points to dist/loader.esm.js. That file has a "export" declaration at the bottom for some reason, and it's fouling up Browserify.

**Comment by StorytellerCZ** [comment] 2019-01-13 18:41
I think this is a duplicate of this issue: https://github.com/filestack/filestack-js/issues/142
Workarounds are in there as well.

**Comment by pcholuj** [comment] 2019-03-15 10:36
Ok this should be resolved with 2.x.x version, problematic module was replaced

**Closed by pcholuj** 2019-03-15 10:36 UTC
