### ISSUE TITLE
Unable to enter text when using bootstrap modal and filestack modal

### ISSUE THREAD

**Issue by jalembke** [filestack/filestack-js#64] opened 2017-11-09 16:54 UTC
So if I use filestack as a file uploader (using the pick function) while a bootstrap modal is displayed, I am not able to use the search or url text fields.  When using the filestack picker directly (without a bootstrap modal) this does not seem to be a problem.  Here is a jsfiddle of what I'm experiencing:

https://jsfiddle.net/bs63dad7/2/

If you click on "Launch modal" and then "Pick File" you can select the url or search menu but you can't enter any text.  If you close everything and then use "Pick File Without modal" then everything with search and url works just fine.

Is there a work around for this that anyone is aware of?

**Comment by velveteer** [comment] 2017-11-09 17:02
This is a duplicate of https://github.com/filestack/filestack-js/issues/1 and is a known bug with Bootstrap modals. I don't know of a current workaround but any ideas are welcome.

**Comment by jalembke** [comment] 2017-11-09 17:12
Sorry about that.  I usually check existing issues for duplicates.  I'll take a look thanks.

**Comment by jalembke** [comment] 2019-02-14 16:36
Been a while, any update on this issue?

**Comment by pcholuj** [comment] 2019-06-07 09:39
HI, with new version of filestack js you can use 
$(document).off('focusin.modal'); 

this should work like in example.

https://jsfiddle.net/reyh57dp/

**Closed by pcholuj** 2019-06-07 09:39 UTC
Labels: bug
