### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by xiaolin** [filestack/filestack-js#12] opened 2017-04-25 20:43 UTC
Hi, I'm attempting to npm install the package and its failing

```
> npm install --save filestack-js
npm ERR! fetch failed http://static.filestackapi.com/packages/api-client/api-client-0.3.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! fetch failed http://static.filestackapi.com/packages/picker/picker-0.5.4.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! fetch failed http://static.filestackapi.com/packages/api-client/api-client-0.3.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! fetch failed http://static.filestackapi.com/packages/picker/picker-0.5.4.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
```

**Comment by velveteer** [comment] 2017-04-25 20:57
Hello @xiaolin, this is a peculiar error. Those tarballs should be readily available, so it seems that npm is doing something odd with the request. Are you currently authenticated with npm? Does running `npm logout` or upgrading npm resolve this issue?

**Comment by xiaolin** [comment] 2017-04-25 21:04
This is odd, I upgraded npm from 3.7.7 to 4.0.0 and its working. Thanks for your help!

**Comment by velveteer** [comment] 2017-04-25 21:12
Sounds like npm being npm. We appreciate the feedback! Since the problem is resolved I will close the issue. :)

**Closed by velveteer** 2017-04-25 21:12 UTC
