### ISSUE TITLE
`CropFiles` breaks drop pane success callback 

### ISSUE THREAD

**Issue by IanVS** [filestack/filestack-js#350] opened 2020-04-23 14:52 UTC
I noticed that my drop panes are no longer working.  I tried turning off `cropFiles`, and they work.  But if I turn cropping on, I never get a call to my `onSuccess` or `onError` callbacks.  I see a few console logs from picker.js, but that's it.

**Comment by wfifer** [comment] 2020-04-24 01:21
Thankfully caught this before demoing some image-based features—our bad for not pegging the version. Looks like 3.12.4 is fine, if that helps for now.

**Comment by pcholuj** [comment] 2020-04-24 05:52
Hi @IanVS 
Can you provide your dropPanel config ?

**Comment by mminkoff** [comment] 2020-06-03 19:54
@pcholuj I can confirm seeing the same behavior on 3.15.0.

```
{
  maxSize: 1024*1024*5,
  imageMax: [1024,1024],
  accept: "image/*",
  displayMode: "dropPane",
  container: "#answer-drop-pane",
  dropPane: {
    onProgress,
    onSuccess,
    customText,
    showIcon: false,
    cropFiles: true
  },
  cleanupImageExif: {
    keepOrientation: true,
    keepICCandAPP: true
  },
  transformations: {
    crop: {
      aspectRatio: 8/6
    },
    rotate: true,
    force: true
  }
}
```

**Comment by IanVS** [comment] 2020-06-04 00:45
Sorry, I've left the team where I hit this issue, I can no longer provide the config, but it looks like @mminkoff has.  Thanks!

**Comment by pcholuj** [comment] 2020-06-30 07:30
We will be checking this problem soon.

**Comment by pcholuj** [comment] 2020-10-05 09:17
Fixed in newest release

**Closed by pcholuj** 2020-10-05 09:17 UTC
Labels: bug, needs more info
