### ISSUE TITLE
Getting "Uncaught SyntaxError: Unexpected token export"

### ISSUE THREAD

**Issue by tbaustin** [filestack/filestack-js#142] opened 2018-08-28 13:09 UTC
I installed this on a gatsby/react application and added it as so:

`import * as filestack from 'filestack-js'` 

This error shows up in the console: `Uncaught SyntaxError: Unexpected token export`

**Comment by ayalpani** [comment] 2018-09-17 10:41
Me too. On a meteor project.

**Comment by ayalpani** [comment] 2018-09-17 11:47
This is how you can reproduce it with my environment:

1. Install meteor js ( https://www.meteor.com/install )
2. Run `meteor create filestack-test`
3. Run `cd filestack-test`
4. Run `npm install --save filestack-js`
5. Edit `client/main.js` and add `import * as filestack from 'filestack-js'`
6. Run `meteor run`
7. Open `http://localhost:3000/`
8. Open browser console and you should see the error message `Uncaught SyntaxError: Unexpected token export`

I am doing this on an Ubuntu 16.04 system

**Comment by JamesDutton** [comment] 2018-10-09 14:42
Did either of you find a fix for this? I've just hit the same issue using filestack-js in a meteor project.

> Uncaught SyntaxError: Unexpected token export

**Comment by ayalpani** [comment] 2018-10-18 12:49
No, I had no success

**Comment by WayneUong** [comment] 2018-10-26 18:00
We're getting the same error

**Comment by nikparo** [comment] 2018-11-13 14:41
Same problem here. I did some regression testing and this is the case since v1.0.0 ...

### The quick solution:

```js
import * as filestack from 'filestack-js/build/browser/index.umd.js';
```

### The problem:

It seems the `package.json` instructs browser builds to load `build/browser/index.esm.js`, but that file ends with the line:
```js
export { init, version, EStyleType, EShapeType, ENoiseType, EFitOptions, EColorspaceType, EBlurMode, EAlignOptions, EAlignFacesOptions, ECropfacesType, getSecurity };
```
Which naturally throws an error in browsers, at least in Meteor projects. I don't know if other build systems parse and bundle node modules? Well, at least it works when pointing straight to the umd version ...

**Comment by WayneUong** [comment] 2018-11-13 16:49
`import filestack from 'filestack-js/build/browser/filestack.min.js';` is a better solution I think.

**Closed** 2020-07-28 12:03 UTC
