### ISSUE TITLE
Cannot read property 'resolvePromise' of undefined

### ISSUE THREAD

**Issue by erohin** [filestack/filestack-js#76] opened 2017-12-07 11:24 UTC
I'm getting this error in filestask-js 0.9.12 and filestack-react 1.3.8
![image](https://user-images.githubusercontent.com/2608959/33712918-311ff3ec-db5a-11e7-8c49-3529af0eda6a.png)
Any thoughts?

**Comment by serenitus** [comment] 2017-12-15 11:30
I see this too on 0.9.12 with a particular user. @erohin have you tried upgrading the library and did that make any difference?

**Comment by velveteer** [comment] 2017-12-15 18:35
It will be very helpful if we can have browser info with steps to reproduce or a JSFiddle/CodePen that effectively reproduces this issue.

**Comment by serenitus** [comment] 2017-12-19 09:46
@velveteer I'm afraid I'm actually unable to reproduce this myself as it's being experienced by one of our own users. We've eliminated browser extensions, VPNs, pop-up/ad blockers, crazy browsing security things that hook into your network stack, etc. Our user sees this on their two machines in the same office.

Browser is Chrome 63 on Windows.

**Comment by erohin** [comment] 2017-12-20 12:20
I think it's related to #57, I also can't reproduce this issue on my machine.
We used latest library version of filestack-js and filestac-react, we tried to downgrade, but with no success. We recently changed our file uploading mechanism because of this bug. It's very rare and unreproducible bug. But we also saw this in latest Chrome on Windows.

**Comment by serenitus** [comment] 2017-12-23 08:57
@velveteer @erohin my user has managed to narrow it down to a Chrome extension (https://livestartpage.com/) and I have subsequently reproduced and confirmed this. By all accounts this is a pretty popular Chrome extension so it would be great to get a fix for this if possible.

**Comment by pcholuj** [comment] 2019-05-15 11:24
this shtould be fixed in 2.x.x

**Closed by pcholuj** 2019-05-15 11:24 UTC
Labels: bug
