### ISSUE TITLE
Force cropping does not take effect in some cases

### ISSUE THREAD

**Issue by crellbar** [filestack/filestack-js#117] opened 2018-06-01 15:21 UTC
Running the example below select an image but do not touch the crop area, simply click save and upload, you should see the that the image that is returned in the response is the original image with no cropping.

If you alter the cropping area at all then the image that is returned in the response is resized.

```
<html>
<head>
    <script src="js/app.js"></script>
    <script>
        window.addEventListener('DOMContentLoaded', function () {
            var apikey = 'YOUR_API_KEY',
                pickerSettings = {
                    transformations: {
                        crop: { aspectRatio: 5, force: true },
                    }
                },
                client = filestack.init(apikey);

            client.pick(pickerSettings).then(function (response) {
                console.log(response);
                document.getElementsByTagName('img')[0].src = response.filesUploaded[0].url;
                return false;
            });
        });
    </script>
</head>
<body>
    <img src="" />
</body>
</html>
```

Also note that that adding the `uploadInBackground` property to the picker settings as below will fix this which suggests the issue is related to eager uploading of selected files when cropping is being enforced.

```
pickerSettings = {
                    transformations: {
                        crop: { aspectRatio: 5, force: true },
                    },
                    uploadInBackground: false
                },
```

Incase it's browser specific, this was on Google Chrome Version 66.0.3359.181 on MacOS High Sierra.

**Comment by velveteer** [comment] 2018-06-01 16:40
@crellbar Thanks for reporting this. It looks like it might be the same issue reported here: https://github.com/filestack/filestack-js/issues/81

There appears to be an incompatibility with `crop.force = true` and `uploadInBackground = true`, and while turning off background uploads is a valid workaround we should prevent this from happening when the config is parsed. I will add this issue to our own backlog and we can plan a patch to resolve it.

**Comment by velveteer** [comment] 2018-06-04 17:42
Closing this since it's a duplicate of https://github.com/filestack/filestack-js/issues/81. We will track this in our backlog.

**Closed by velveteer** 2018-06-04 17:42 UTC
