### ISSUE TITLE
Upload sources buttons and view/edit bar disappears on safari when hovering 

### ISSUE THREAD

**Issue by darkowic** [filestack/filestack-js#308] opened 2019-12-04 15:24 UTC
Sources buttons and edit bar disappears on safari when hovering on picker:
![filestack_dialog_issue](https://user-images.githubusercontent.com/11510581/70155429-86d02880-16b2-11ea-8191-d20154209b02.gif)
The video with reproduction:
[filestack_dialog_issue.mp4.zip](https://github.com/filestack/filestack-js/files/3922565/filestack_dialog_issue.mp4.zip)

Reproduction case: https://codesandbox.io/s/safari-filestack-bug-ijqmg

I open the picker in inline mode in material-ui dialog. See the reproduction case.

Safari: 13.0.3

**Comment by maryfs** [comment] 2020-01-08 10:29
Hi @darkowic ,
thanks for code snippet, it will be fixed.

**Comment by maryfs** [comment] 2020-09-28 07:41
Hi @darkowic 
Could you try with new versions? 
I cannot reproduce it.
Thanks

**Comment by darkowic** [comment] 2020-09-28 07:56
@TomekStaszkiewicz

**Comment by TomekStaszkiewicz** [comment] 2020-09-30 11:31
@darkowic @maryfs I also cannot reproduce this issue with new versions. It seems that it was fixed. 👍

**Comment by maryfs** [comment] 2020-09-30 13:03
@TomekStaszkiewicz  thanks.

**Closed by maryfs** 2020-09-30 13:03 UTC
Labels: bug
