### ISSUE TITLE
"XML Parsing Error: no root element found" on upload

### ISSUE THREAD

**Issue by tlshaheen** [filestack/filestack-js#3] opened 2017-03-12 01:50 UTC
Getting a `XML Parsing Error: no root element found` after I upload a file in Firefox. Using v0.2.1.

I'm surprised there is an error since I have a very basic setup. What am I missing?

Edit: I'm seeing the same error in the console when [trying the demos on Filestack's website](https://filestack.com/docs/javascript-api/picker-recipes-v3)

<img width="1439" alt="screen shot 2017-03-11 at 8 42 35 pm" src="https://cloud.githubusercontent.com/assets/385724/23828308/37bd3072-069c-11e7-896b-d58ba02bce5b.png">

My code:
```
let filestackClient = filestack.init('mykey');
filestackClient.pick({
    maxFiles: 1,
    accept: ['image/*'],
    startUploadingWhenMaxFilesReached: true,
    fromSources: ['local_file_system', 'facebook']
})
```

**Comment by velveteer** [comment] 2017-03-12 02:54
Hey @tlshaheen, thanks for reporting this. I was able to replicate the issue in Firefox 52. Is this error causing upload failures on your end? When reproducing it didn't seem to halt the upload flow.

We'll look into this and let you know what we find.

**Comment by tlshaheen** [comment] 2017-03-12 03:23
@velveteer No upload failures on my end, just the warning in the console!

**Comment by tlshaheen** [comment] 2017-03-12 14:12
@velveteer Are you planning on publishing the `src` for filestack-js instead of just the compacted `dist`? I'd love to be able to help contribute. Or, is there a way for me to de-compact fielstack.js? It doesn't seem to be quite minified, just compacted/obscured.

**Comment by velveteer** [comment] 2017-07-04 19:51
There is no source code in this repo, but maybe someday. It's something I can push for if enough users are asking for it. 

As for this Firefox issue, it doesn't seem to affect functionality of the SDK, and I think it's related to how Firefox parses a 200 response with an empty body. It's a long-standing Firefox issue, and it will not be addressed in the SDK for now.

**Closed by velveteer** 2017-07-04 19:51 UTC
Labels: bug

**Comment by meniossin** [comment] 2018-05-07 08:42
Greetings,
I'm trying to integrate the filestack api in a shopify store I'm currently working on. When I test the functionality of uploading an image with Firefox(60.0b16 (64-bit) on Ubuntu 16.04) I'm getting the same error after the upload bar finishes loading, "XML Parsing Error: no root element found ". I tried replicating the issue in Chromium (Version 65.0.3325.181 ) and the error does not occur there. Any thoughts ? Is  this considered a bug without solution ? Let me know, thanks in advance.

**Comment by thomaslange24** [comment] 2019-06-25 07:52
I also would like this issue to be reopened since i am facing the same Problem with a multipart upload from the browser. For me it also causes the upload to fail. This happens in Firefox, but not in Google Chrome. I am using EvaporateJs for the multipart upload.
